spring:
  application:
    name: discovery
    #routes:
    #  endpoints: env,metrics,trace,dump,jolokia,info,configprops,trace,logfile,refresh #,flyway,liquibase,heapdump
server:
  port: 8761 # 指定该Eureka实例的端口
eureka:
  instance:
    hostname: localhost # 指定该Eureka实例的主机名
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  server:
    enableSelfPreservation: false
    evictionIntervalTimerInMs: 3000
logging:
  level: debug
